services:
  - type: web
    name: profcalendar-clean
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "flask db upgrade && gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: FLASK_ENV
        value: production
      - key: UPLOAD_FOLDER
        value: /opt/render/project/src/uploads
    disk:
      name: profcalendar-storage
      mountPath: /opt/render/project/src/uploads
      sizeGB: 1